### ISSUE TITLE
Plotly: Stretch goals

### ISSUE THREAD

**Issue by ewels** [MultiQC/MultiQC#2311]
```[tasklist]
### Tasks
- [ ] https://github.com/MultiQC/MultiQC/issues/2302
- [ ] https://github.com/MultiQC/MultiQC/issues/2307
- [ ] https://github.com/MultiQC/MultiQC/issues/297
- [ ] https://github.com/MultiQC/MultiQC/issues/876
- [ ] https://github.com/MultiQC/MultiQC/issues/1102
- [ ] https://github.com/MultiQC/MultiQC/issues/1934
- [ ] https://github.com/MultiQC/MultiQC/issues/2214
- [ ] https://github.com/MultiQC/MultiQC/issues/2324
- [ ] https://github.com/MultiQC/MultiQC/issues/2367
```

**Comment by ewels** [comment]
Merging into https://github.com/MultiQC/MultiQC/issues/2407
