### ISSUE TITLE
Folder multiqc_plots not populated with multiqc 1.22.2

### ISSUE THREAD

**Issue by d4straub** [MultiQC/MultiQC#2632]
### Description of bug

I updated from nf-core module with multiqc version 1.21 to 1.22.2 and suddenly the folder `multiqc_plots` isnt filled any more. Am I missing something or is this a bug?

This is in nf-core/ampliseq pipeline and the contents of `multiqc_config.yml`:
```yaml
report_comment: >
  This report has been generated by the <a href="https://github.com/nf-core/ampliseq/tree/dev" target="_blank">nf-core/ampliseq</a>
  analysis pipeline. For information about how to interpret these results, please see the
  <a href="https://nf-co.re/ampliseq/dev/docs/output" target="_blank">documentation</a>.
report_section_order:
  "nf-core-ampliseq-methods-description":
    order: -1000
  software_versions:
    order: -1001
  "nf-core-ampliseq-summary":
    order: -1002

export_plots: true

disable_version_detection: true

# MultiQC version 1.20 & 1.21 need that flag to produce plots!
# TODO: Remove with version greater than 1.21!
plots_force_flat: true
```

### File that triggers the error

[MultiQC_issue_plots.zip](https://github.com/user-attachments/files/15901396/MultiQC_issue_plots.zip)

### MultiQC Error log

This is the .command.log of the relevant work directory.
```console
/// MultiQC 🔍 v1.22.2

            config | Loading config settings from: multiqc_config.yml
            config | Loading config settings from: multiqc_config.yml
       file_search | Search path: /home/daniel/Desktop/github-ampliseq/work/4f/44118990db9faf2bcc5b6f8dc687bb

    custom_content | nf-core-ampliseq-summary: Found 1 sample (html)
    custom_content | nf-core-ampliseq-methods-description: Found 1 sample (html)
          cutadapt | Found 4 reports
            fastqc | Found 8 reports
     write_results | Data        : multiqc_data
     write_results | Report      : multiqc_report.html
     write_results | Plots       : multiqc_plots
           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [x] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Fixed now with https://github.com/MultiQC/MultiQC/pull/2637
Sorry about this issue!
